# Generated by Django 4.2.21 on 2025-06-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandStagePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('demand_to_be_initiated', 'Demand to be Initiated'), ('demand_initiated', 'Demand Initiated'), ('spc_cleared', 'SPC Cleared'), ('demand_approved', 'Demand Approved'), ('tender_enquiry_floated', 'Tender Enquiry Floated'), ('receipt_of_quotations', 'Receipt of Quotations'), ('tender_opening', 'Tender Opening'), ('tcec_approved', 'TCEC Approved'), ('tpc_approved', 'TPC Approved'), ('financial_sanction', 'Financial Sanction'), ('order_placement', 'Order Placement'), ('pdr', 'PDR'), ('so_for_critical_bom_by_dev_partner', 'SO for Critical BoM by Dev Partner'), ('ddr', 'DDR'), ('cdr', 'CDR'), ('acceptance_of_critical_bom_by_dev_partner', 'Acceptance of Critical BoM by Dev Partner'), ('realization_completed', 'Realization Completed'), ('fat_completed', 'FAT Completed'), ('atp_qtp_completed', 'ATP/QTP Completed'), ('delivery_at_stores', 'Delivery at Stores'), ('sat_soft', 'SAT/SoFT'), ('inward_inspection_clearance', 'Inward Inspection Clearance'), ('payment_process', 'Payment Process'), ('partially_paid', 'Partially Paid'), ('payment_released', 'Payment Released'), ('available_for_integration', 'Available for Integration')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='trackerapp.demand')),
            ],
            options={
                'unique_together': {('demand', 'stage')},
            },
        ),
    ]
