# Generated by Django 5.2.1 on 2025-06-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
