# Generated by Django 5.2.1 on 2025-07-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_demand_duration_months_demand_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='demand_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='demand_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='io_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
