# Generated by Django 5.2.1 on 2025-07-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0003_demand_demand_id_demand_demand_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='file_subtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
