# Generated by Django 5.2.1 on 2025-07-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0004_demand_file_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='file_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
