# Generated by Django 5.2.1 on 2025-07-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0005_demand_file_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='weekly_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='weekly_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
