# Generated by Django 5.2.3 on 2025-07-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0006_demand_weekly_end_date_demand_weekly_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('current_stage', models.CharField(blank=True, choices=[('demand_to_be_initiated', 'Demand to be Initiated'), ('demand_initiated', 'Demand Initiated'), ('spc_cleared', 'SPC Cleared'), ('demand_approved', 'Demand Approved'), ('tender_enquiry_floated', 'Tender Enquiry Floated'), ('receipt_of_quotations', 'Receipt of Quotations'), ('tender_opening', 'Tender Opening'), ('tcec_approved', 'TCEC Approved'), ('tpc_approved', 'TPC Approved'), ('financial_sanction', 'Financial Sanction'), ('order_placement', 'Order Placement'), ('pdr', 'PDR'), ('so_for_critical_bom_by_dev_partner', 'SO for Critical BoM by Dev Partner'), ('ddr', 'DDR'), ('cdr', 'CDR'), ('acceptance_of_critical_bom_by_dev_partner', 'Acceptance of Critical BoM by Dev Partner'), ('realization_completed', 'Realization Completed'), ('fat_completed', 'FAT Completed'), ('atp_qtp_completed', 'ATP/QTP Completed'), ('delivery_at_stores', 'Delivery at Stores'), ('sat_soft', 'SAT/SoFT'), ('inward_inspection_clearance', 'Inward Inspection Clearance'), ('payment_process', 'Payment Process'), ('partially_paid', 'Partially Paid'), ('payment_released', 'Payment Released'), ('available_for_integration', 'Available for Integration')], max_length=50, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('next_week_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_updates', to='trackerapp.demand')),
            ],
            options={
                'ordering': ['-week_number'],
                'unique_together': {('demand', 'week_number')},
            },
        ),
    ]
