# Generated by Django 5.2.3 on 2025-07-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0007_weeklyupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='selected_stages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
